name: fastaudio
channels:
  - defaults
  - fastai
  - pytorch
  - conda-forge
dependencies:
  - python>=3.6
  - fastai>=2.0
  - pytorch
  - cudatoolkit=10.1
  - librosa
  - soundfile
  - pip:
    - colorednoise
