name: asr_keras
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - cudatoolkit=10.1
  - cudnn
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - tensorflow-gpu
     - tensorflow-io
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - black
